"""Generated by mpl_visual_editor.

Import this file after your original plotting code and call apply_style(fig).
"""

STYLE_PATCHES = [{'kind': 'axes',
  'path': ('axes', 0),
  'props': {'facecolor': '#ffffff',
            'title': '',
            'xgrid': True,
            'xlabel': 'Time',
            'ygrid': True,
            'ylabel': 'Throughput'}},
 {'kind': 'text',
  'path': ('axes', 0, 'title'),
  'props': {'color': '#000000',
            'fontsize': 12.0,
            'fontstyle': 'normal',
            'fontweight': 'normal',
            'text': ''}},
 {'kind': 'text',
  'path': ('axes', 0, 'xlabel'),
  'props': {'color': '#000000',
            'fontsize': 10.0,
            'fontstyle': 'normal',
            'fontweight': 'normal',
            'text': 'Time'}},
 {'kind': 'text',
  'path': ('axes', 0, 'ylabel'),
  'props': {'color': '#000000',
            'fontsize': 10.0,
            'fontstyle': 'normal',
            'fontweight': 'normal',
            'text': 'Throughput'}},
 {'kind': 'line',
  'path': ('axes', 0, 'lines', 0),
  'props': {'alpha': None,
            'color': '#1f77b4',
            'label': 'A',
            'linestyle': '-',
            'linewidth': 1.5,
            'marker': 'o',
            'markersize': 6.0}},
 {'kind': 'line',
  'path': ('axes', 0, 'lines', 1),
  'props': {'alpha': None,
            'color': '#ff7f0e',
            'label': 'B',
            'linestyle': '-',
            'linewidth': 1.5,
            'marker': 's',
            'markersize': 6.0}},
 {'kind': 'legend',
  'path': ('axes', 0, 'legend'),
  'props': {'edgecolor': '#cccccc',
            'facecolor': '#ffffff',
            'fontsize': 10.0,
            'frame_alpha': 0.8,
            'frame_on': True,
            'visible': True}},
 {'kind': 'spine',
  'path': ('axes', 0, 'spines', 'left'),
  'props': {'color': '#000000', 'linewidth': 0.8, 'visible': True}},
 {'kind': 'spine',
  'path': ('axes', 0, 'spines', 'right'),
  'props': {'color': '#000000', 'linewidth': 0.8, 'visible': True}},
 {'kind': 'spine',
  'path': ('axes', 0, 'spines', 'bottom'),
  'props': {'color': '#000000', 'linewidth': 0.8, 'visible': True}},
 {'kind': 'spine',
  'path': ('axes', 0, 'spines', 'top'),
  'props': {'color': '#000000', 'linewidth': 0.8, 'visible': True}}]


def _resolve(fig, path):
    parts = tuple(path)
    ax = fig.axes[int(parts[1])]
    if len(parts) == 2:
        return ax
    target = parts[2]
    if target == "title":
        return ax.title
    if target == "xlabel":
        return ax.xaxis.label
    if target == "ylabel":
        return ax.yaxis.label
    if target == "lines":
        return ax.lines[int(parts[3])]
    if target == "legend":
        return ax.get_legend()
    if target == "spines":
        return ax.spines[str(parts[3])]
    raise ValueError(f"Unsupported path: {path!r}")


def apply_style(fig):
    """Apply exported visual styling to a Matplotlib Figure."""

    for patch in STYLE_PATCHES:
        artist = _resolve(fig, patch["path"])
        if artist is None:
            continue
        kind = patch["kind"]
        props = patch["props"]

        if kind == "axes":
            artist.set_facecolor(props["facecolor"])
            artist.set_xlabel(props["xlabel"])
            artist.set_ylabel(props["ylabel"])
            artist.set_title(props["title"])
            artist.grid(bool(props["xgrid"]), axis="x")
            artist.grid(bool(props["ygrid"]), axis="y")
        elif kind == "line":
            artist.set_color(props["color"])
            artist.set_linewidth(props["linewidth"])
            artist.set_linestyle(props["linestyle"])
            artist.set_marker(props["marker"])
            artist.set_markersize(props["markersize"])
            artist.set_alpha(props["alpha"])
            artist.set_label(props["label"])
        elif kind == "text":
            artist.set_text(props["text"])
            artist.set_color(props["color"])
            artist.set_fontsize(props["fontsize"])
            artist.set_fontweight(props["fontweight"])
            artist.set_fontstyle(props["fontstyle"])
        elif kind == "legend":
            artist.set_visible(props["visible"])
            for text in artist.get_texts():
                if props["fontsize"] is not None:
                    text.set_fontsize(props["fontsize"])
            frame = artist.get_frame()
            frame.set_visible(props["frame_on"])
            frame.set_alpha(props["frame_alpha"])
            frame.set_facecolor(props["facecolor"])
            frame.set_edgecolor(props["edgecolor"])
        elif kind == "spine":
            artist.set_visible(props["visible"])
            artist.set_edgecolor(props["color"])
            artist.set_linewidth(props["linewidth"])

    fig.canvas.draw_idle()
    return fig
