"""Export current figure styling as a replayable Python patch."""

from __future__ import annotations

from pathlib import Path
from pprint import pformat
from typing import Any
import math

import numpy as np
from matplotlib.collections import PathCollection
from matplotlib.figure import Figure
from matplotlib.lines import Line2D
from matplotlib.markers import MarkerStyle
from matplotlib.patches import Patch
from matplotlib.path import Path as MplPath

from .inspector import iter_artist_refs
from .snapshots import snapshot_artist
from .shapes import apply_shape_props, apply_textbox_props


def export_style(fig: Figure, path: str | Path = "style_patch.py", source: str | None = None) -> Path:
    """Write an ``apply_style(fig)`` function for supported artists."""

    output = Path(path)
    patches = [snapshot_artist(ref.kind, ref.path, ref.artist, for_export=True) for ref in iter_artist_refs(fig)]
    patches = [patch for patch in patches if patch["props"]]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(_render_module(patches, source=source), encoding="utf-8")
    return output


_snapshot = snapshot_artist


def _legend_handles_from_specs(specs: list[dict[str, Any]]) -> list[Any]:
    handles: list[Any] = []
    for spec in specs:
        if spec.get("kind") == "patch":
            handles.append(
                Patch(
                    facecolor=spec.get("facecolor"),
                    edgecolor=spec.get("edgecolor"),
                    linewidth=spec.get("linewidth", 1.0),
                    hatch=spec.get("hatch", ""),
                    label=spec.get("label", ""),
                    alpha=spec.get("alpha"),
                )
            )
        elif spec.get("kind") == "scatter":
            marker = spec.get("marker") or _marker_from_path_spec(spec.get("path"))
            if marker is not None:
                handles.append(
                    Line2D(
                        [],
                        [],
                        linestyle="None",
                        marker=marker,
                        markersize=math.sqrt(float(spec.get("size", 36.0))),
                        markerfacecolor=spec.get("facecolor"),
                        markeredgecolor=spec.get("edgecolor"),
                        markeredgewidth=spec.get("linewidth", 1.0),
                        label=spec.get("label", ""),
                        alpha=spec.get("alpha"),
                    )
                )
            else:
                path_spec = spec.get("path") or {}
                marker_path = MplPath(path_spec.get("vertices", []), path_spec.get("codes"))
                handles.append(
                    PathCollection(
                        [marker_path],
                        sizes=[spec.get("size", 36.0)],
                        facecolors=[spec.get("facecolor")],
                        edgecolors=[spec.get("edgecolor")],
                        linewidths=[spec.get("linewidth", 1.0)],
                        label=spec.get("label", ""),
                        alpha=spec.get("alpha"),
                    )
                )
        elif spec.get("kind") == "line":
            handles.append(
                Line2D(
                    [],
                    [],
                    color=spec.get("color"),
                    linewidth=spec.get("linewidth", 1.0),
                    linestyle=spec.get("linestyle", "-"),
                    marker=spec.get("marker", "None"),
                    markersize=spec.get("markersize", 6.0),
                    label=spec.get("label", ""),
                    alpha=spec.get("alpha"),
                )
            )
    return handles


def _marker_from_path_spec(path_spec: dict[str, Any] | None) -> str | None:
    if not path_spec:
        return None
    path = MplPath(path_spec.get("vertices", []), path_spec.get("codes"))
    for marker in ["x", "o", "s", "^", "v", "D", "+", "*", ".", "P", "X"]:
        marker_style = MarkerStyle(marker)
        marker_path = marker_style.get_path().transformed(marker_style.get_transform())
        if _paths_match(path, marker_path):
            return marker
    return None


def _paths_match(left: Any, right: Any) -> bool:
    left_codes = getattr(left, "codes", None)
    right_codes = getattr(right, "codes", None)
    if left_codes is None and right_codes is not None:
        return False
    if left_codes is not None and right_codes is None:
        return False
    if left_codes is not None and not np.array_equal(left_codes, right_codes):
        return False
    return np.allclose(left.vertices, right.vertices, rtol=1e-6, atol=1e-8)


def _render_module(patches: list[dict[str, Any]], source: str | None = None) -> str:
    source_repr = repr(source)
    return f'''"""Generated by mpl_visual_editor.

Import this file after your original plotting code and call apply_style(fig).
"""

import math
import warnings

from matplotlib.collections import PathCollection
from matplotlib.lines import Line2D
from matplotlib.markers import MarkerStyle
from matplotlib.patches import Patch
from matplotlib.path import Path
import numpy as np

from mpl_visual_editor.shapes import apply_shape_props, apply_textbox_props

MPL_VISUAL_EDITOR_SOURCE = {source_repr}

STYLE_PATCHES = {pformat(patches, width=100)}


def _resolve(fig, path):
    parts = tuple(path)
    if parts == ("figure",):
        return fig
    ax = fig.axes[int(parts[1])]
    if len(parts) == 2:
        return ax
    target = parts[2]
    if target == "title":
        return ax.title
    if target == "xlabel":
        return ax.xaxis.label
    if target == "ylabel":
        return ax.yaxis.label
    if target == "texts":
        return ax.texts[int(parts[3])]
    if target == "texts_group":
        return tuple(ax.texts)
    if target == "mve_shapes":
        editor_id = str(parts[3])
        for patch in ax.patches:
            if getattr(patch, "_mve_kind", None) == "shape" and getattr(patch, "_mve_id", None) == editor_id:
                return patch
        raise ValueError(f"No editor shape for path: {{path!r}}")
    if target == "mve_textboxes":
        editor_id = str(parts[3])
        for text in ax.texts:
            if getattr(text, "_mve_kind", None) == "textbox" and getattr(text, "_mve_id", None) == editor_id:
                return text
        raise ValueError(f"No editor text box for path: {{path!r}}")
    if target == "xaxis":
        return ax.xaxis
    if target == "yaxis":
        return ax.yaxis
    if target == "lines":
        return ax.lines[int(parts[3])]
    if target == "collections":
        return ax.collections[int(parts[3])]
    if target == "containers":
        return ax.containers[int(parts[3])]
    if target == "legend":
        return ax.get_legend()
    if target == "spines":
        return ax.spines[str(parts[3])]
    raise ValueError(f"Unsupported path: {{path!r}}")


def apply_style(fig):
    """Apply exported visual styling to a Matplotlib Figure."""

    for patch in STYLE_PATCHES:
        kind = patch["kind"]
        props = patch["props"]
        if kind == "shape":
            ax = fig.axes[int(patch["path"][1])]
            apply_shape_props(ax, props)
            continue
        if kind == "textbox":
            ax = fig.axes[int(patch["path"][1])]
            apply_textbox_props(ax, props)
            continue
        artist = _resolve(fig, patch["path"])
        if artist is None:
            continue

        if kind == "figure":
            artist.set_size_inches(props["width"], props["height"], forward=True)
            artist._mve_width = float(props["width"])
            artist._mve_height = float(props["height"])
        elif kind == "axes":
            artist.set_facecolor(props["facecolor"])
            artist.set_xlabel(props["xlabel"])
            artist.set_ylabel(props["ylabel"])
            artist.set_title(props["title"])
            artist.grid(bool(props["xgrid"]), axis="x")
            artist.grid(bool(props["ygrid"]), axis="y")
        elif kind == "line":
            artist.set_color(props["color"])
            artist.set_linewidth(props["linewidth"])
            artist.set_linestyle(props["linestyle"])
            artist.set_marker(props["marker"])
            artist.set_markersize(props["markersize"])
            artist.set_alpha(props["alpha"])
            artist.set_label(props["label"])
        elif kind == "scatter":
            artist.set_visible(props["visible"])
            artist.set_label(props["label"])
            artist.set_facecolor(props["facecolor"])
            artist.set_edgecolor(props["edgecolor"])
            artist.set_linewidth(props["linewidth"])
            artist.set_sizes([props["size"]] * max(1, len(artist.get_offsets())))
            artist.set_alpha(props["alpha"])
        elif kind == "bar":
            artist.set_label(props["label"])
            for index, patch in enumerate(artist.patches):
                patch.set_visible(_list_prop(props, "visible", index))
                patch.set_facecolor(_list_prop(props, "facecolor", index))
                patch.set_edgecolor(_list_prop(props, "edgecolor", index))
                patch.set_linewidth(_list_prop(props, "linewidth", index))
                patch.set_alpha(_list_prop(props, "alpha", index))
                patch.set_hatch(_list_prop(props, "hatch", index) or "")
                _set_bar_width_centered(patch, _list_prop(props, "width", index))
        elif kind == "text":
            artist.set_text(props["text"])
            artist.set_color(props["color"])
            artist.set_fontsize(props["fontsize"])
            artist.set_fontweight(props["fontweight"])
            artist.set_fontstyle(props["fontstyle"])
        elif kind == "text_group":
            for text in artist:
                text.set_color(props["color"])
                text.set_fontsize(props["fontsize"])
                text.set_fontweight(props["fontweight"])
                text.set_fontstyle(props["fontstyle"])
        elif kind == "axis":
            ax = artist.axes
            axis_name = props["axis"]
            if props.get("scale_explicit"):
                if axis_name == "x":
                    ax.set_xscale(props["scale"])
                else:
                    ax.set_yscale(props["scale"])
            if props.get("ticks_explicit"):
                _apply_axis_ticks(ax, axis_name, props["tick_start"], props["tick_interval"], props.get("tick_end"))
            if props.get("tick_labels_explicit"):
                _apply_axis_tick_labels(
                    artist,
                    props["tick_label_fontsize"],
                    props["tick_label_color"],
                    props["tick_label_weight"],
                    props["tick_label_style"],
                    props["tick_label_rotation"],
                )
        elif kind == "legend":
            ax = artist.axes
            handles = _legend_handles_from_specs(props.get("handle_specs", []))
            artist = ax.legend(
                handles=handles or None,
                loc=props["loc"],
                bbox_to_anchor=props["bbox_to_anchor"],
                ncols=props["ncols"],
                fontsize=props["fontsize"],
                frameon=props["frame_on"],
                borderpad=props["borderpad"],
                labelspacing=props["labelspacing"],
                handlelength=props["handlelength"],
                handletextpad=props["handletextpad"],
                borderaxespad=props["borderaxespad"],
                columnspacing=props["columnspacing"],
            )
            artist.set_visible(props["visible"])
            for text in artist.get_texts():
                if props["fontsize"] is not None:
                    text.set_fontsize(props["fontsize"])
            frame = artist.get_frame()
            frame.set_visible(props["frame_on"])
            frame.set_alpha(props["frame_alpha"])
            frame.set_facecolor(props["facecolor"])
            frame.set_edgecolor(props["edgecolor"])
        elif kind == "spine":
            artist.set_visible(props["visible"])
            artist.set_edgecolor(props["color"])
            artist.set_linewidth(props["linewidth"])

    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            fig.tight_layout()
    except Exception:
        pass
    fig.canvas.draw_idle()
    return fig


def _apply_axis_ticks(ax, axis_name, start, interval, end=None):
    interval = float(interval)
    start = float(start)
    if end is not None:
        end = float(end)
    if (
        interval <= 0
        or not math.isfinite(interval)
        or not math.isfinite(start)
        or (end is not None and not math.isfinite(end))
    ):
        return
    if axis_name == "x":
        low, high = ax.get_xlim()
    else:
        low, high = ax.get_ylim()
    inverted = high < low
    if high < low:
        low, high = high, low
    ticks = []
    value = start
    low = value
    if end is not None:
        high = max(start, end)
    if high <= low:
        high = low + interval
    limit = high + interval * 0.5
    max_ticks = 1000
    while value <= limit and len(ticks) < max_ticks:
        if math.isfinite(value):
            ticks.append(value)
        value += interval
    if len(ticks) >= max_ticks:
        high = ticks[-1]
    if axis_name == "x":
        ax.set_xticks(ticks)
        ax.set_xlim((high, low) if inverted else (low, high))
        ax.xaxis._mve_tick_start = start
        ax.xaxis._mve_tick_end = high
        ax.xaxis._mve_tick_interval = interval
    else:
        ax.set_yticks(ticks)
        ax.set_ylim((high, low) if inverted else (low, high))
        ax.yaxis._mve_tick_start = start
        ax.yaxis._mve_tick_end = high
        ax.yaxis._mve_tick_interval = interval


def _list_prop(props, name, index):
    plural_name = "hatches" if name == "hatch" else f"{{name}}s"
    values = props.get(plural_name)
    if values is None:
        return props.get(name)
    if not values:
        return None
    return values[min(index, len(values) - 1)]


def _set_bar_width_centered(patch, width):
    width = float(width)
    old_width = float(patch.get_width())
    center = float(patch.get_x()) + old_width / 2.0
    signed_width = math.copysign(width, old_width if old_width else 1.0)
    patch.set_width(signed_width)
    patch.set_x(center - signed_width / 2.0)


def _legend_handles_from_specs(specs):
    handles = []
    for spec in specs:
        if spec.get("kind") == "patch":
            handles.append(
                Patch(
                    facecolor=spec.get("facecolor"),
                    edgecolor=spec.get("edgecolor"),
                    linewidth=spec.get("linewidth", 1.0),
                    hatch=spec.get("hatch", ""),
                    label=spec.get("label", ""),
                    alpha=spec.get("alpha"),
                )
            )
        elif spec.get("kind") == "scatter":
            marker = spec.get("marker") or _marker_from_path_spec(spec.get("path"))
            if marker is not None:
                handles.append(
                    Line2D(
                        [],
                        [],
                        linestyle="None",
                        marker=marker,
                        markersize=math.sqrt(float(spec.get("size", 36.0))),
                        markerfacecolor=spec.get("facecolor"),
                        markeredgecolor=spec.get("edgecolor"),
                        markeredgewidth=spec.get("linewidth", 1.0),
                        label=spec.get("label", ""),
                        alpha=spec.get("alpha"),
                    )
                )
            else:
                path_spec = spec.get("path") or {{}}
                marker_path = Path(path_spec.get("vertices", []), path_spec.get("codes"))
                handles.append(
                    PathCollection(
                        [marker_path],
                        sizes=[spec.get("size", 36.0)],
                        facecolors=[spec.get("facecolor")],
                        edgecolors=[spec.get("edgecolor")],
                        linewidths=[spec.get("linewidth", 1.0)],
                        label=spec.get("label", ""),
                        alpha=spec.get("alpha"),
                    )
                )
        elif spec.get("kind") == "line":
            handles.append(
                Line2D(
                    [],
                    [],
                    color=spec.get("color"),
                    linewidth=spec.get("linewidth", 1.0),
                    linestyle=spec.get("linestyle", "-"),
                    marker=spec.get("marker", "None"),
                    markersize=spec.get("markersize", 6.0),
                    label=spec.get("label", ""),
                    alpha=spec.get("alpha"),
                )
            )
    return handles


def _marker_from_path_spec(path_spec):
    if not path_spec:
        return None
    path = Path(path_spec.get("vertices", []), path_spec.get("codes"))
    for marker in ["x", "o", "s", "^", "v", "D", "+", "*", ".", "P", "X"]:
        marker_style = MarkerStyle(marker)
        marker_path = marker_style.get_path().transformed(marker_style.get_transform())
        if _paths_match(path, marker_path):
            return marker
    return None


def _paths_match(left, right):
    left_codes = getattr(left, "codes", None)
    right_codes = getattr(right, "codes", None)
    if left_codes is None and right_codes is not None:
        return False
    if left_codes is not None and right_codes is None:
        return False
    if left_codes is not None and not np.array_equal(left_codes, right_codes):
        return False
    return np.allclose(left.vertices, right.vertices, rtol=1e-6, atol=1e-8)


def _apply_axis_tick_labels(axis, fontsize, color, weight, style, rotation):
    axis._mve_tick_label_fontsize = float(fontsize)
    axis._mve_tick_label_color = color
    axis._mve_tick_label_fontweight = weight
    axis._mve_tick_label_fontstyle = style
    axis._mve_tick_label_rotation = float(rotation)
    for label in axis.get_ticklabels():
        label.set_fontsize(float(fontsize))
        label.set_color(color)
        label.set_fontweight(weight)
        label.set_fontstyle(style)
        label.set_rotation(float(rotation))
'''
