"""Export current figure styling as a replayable Python patch."""

from __future__ import annotations

from pathlib import Path
from pprint import pformat
from typing import Any

from matplotlib.colors import to_hex
from matplotlib.figure import Figure

from .inspector import iter_artist_refs


def export_style(fig: Figure, path: str | Path = "style_patch.py") -> Path:
    """Write an ``apply_style(fig)`` function for supported artists."""

    output = Path(path)
    patches = [_snapshot(ref.kind, ref.path, ref.artist) for ref in iter_artist_refs(fig)]
    patches = [patch for patch in patches if patch["props"]]
    output.write_text(_render_module(patches), encoding="utf-8")
    return output


def _snapshot(kind: str, artist_path: tuple[Any, ...], artist: Any) -> dict[str, Any]:
    props: dict[str, Any] = {}

    if kind == "axes":
        props = {
            "facecolor": _color(artist.get_facecolor()),
            "xlabel": artist.get_xlabel(),
            "ylabel": artist.get_ylabel(),
            "title": artist.get_title(),
            "xgrid": any(line.get_visible() for line in artist.get_xgridlines()),
            "ygrid": any(line.get_visible() for line in artist.get_ygridlines()),
        }
    elif kind == "line":
        props = {
            "color": _color(artist.get_color()),
            "linewidth": float(artist.get_linewidth()),
            "linestyle": artist.get_linestyle(),
            "marker": artist.get_marker(),
            "markersize": float(artist.get_markersize()),
            "alpha": artist.get_alpha(),
            "label": artist.get_label(),
        }
    elif kind == "text":
        props = {
            "text": artist.get_text(),
            "color": _color(artist.get_color()),
            "fontsize": float(artist.get_fontsize()),
            "fontweight": artist.get_fontweight(),
            "fontstyle": artist.get_fontstyle(),
        }
    elif kind == "legend":
        frame = artist.get_frame()
        props = {
            "visible": bool(artist.get_visible()),
            "fontsize": _legend_fontsize(artist),
            "loc": getattr(artist, "_mve_loc", getattr(artist, "_loc", "best")),
            "bbox_to_anchor": getattr(artist, "_mve_bbox_to_anchor", None),
            "ncols": getattr(artist, "_ncols", 1),
            "frame_on": bool(frame.get_visible()),
            "frame_alpha": frame.get_alpha(),
            "facecolor": _color(frame.get_facecolor()),
            "edgecolor": _color(frame.get_edgecolor()),
            "borderpad": float(artist.borderpad),
            "labelspacing": float(artist.labelspacing),
            "handlelength": float(artist.handlelength),
            "handletextpad": float(artist.handletextpad),
            "borderaxespad": float(artist.borderaxespad),
            "columnspacing": float(artist.columnspacing),
        }
    elif kind == "spine":
        props = {
            "visible": bool(artist.get_visible()),
            "color": _color(artist.get_edgecolor()),
            "linewidth": float(artist.get_linewidth()),
        }

    return {"kind": kind, "path": artist_path, "props": props}


def _legend_fontsize(legend: Any) -> float | None:
    texts = legend.get_texts()
    if not texts:
        return None
    return float(texts[0].get_fontsize())


def _color(value: Any) -> str | None:
    if value is None:
        return None
    try:
        return to_hex(value, keep_alpha=False)
    except ValueError:
        return str(value)


def _render_module(patches: list[dict[str, Any]]) -> str:
    return f'''"""Generated by mpl_visual_editor.

Import this file after your original plotting code and call apply_style(fig).
"""

STYLE_PATCHES = {pformat(patches, width=100)}


def _resolve(fig, path):
    parts = tuple(path)
    ax = fig.axes[int(parts[1])]
    if len(parts) == 2:
        return ax
    target = parts[2]
    if target == "title":
        return ax.title
    if target == "xlabel":
        return ax.xaxis.label
    if target == "ylabel":
        return ax.yaxis.label
    if target == "lines":
        return ax.lines[int(parts[3])]
    if target == "legend":
        return ax.get_legend()
    if target == "spines":
        return ax.spines[str(parts[3])]
    raise ValueError(f"Unsupported path: {{path!r}}")


def apply_style(fig):
    """Apply exported visual styling to a Matplotlib Figure."""

    for patch in STYLE_PATCHES:
        artist = _resolve(fig, patch["path"])
        if artist is None:
            continue
        kind = patch["kind"]
        props = patch["props"]

        if kind == "axes":
            artist.set_facecolor(props["facecolor"])
            artist.set_xlabel(props["xlabel"])
            artist.set_ylabel(props["ylabel"])
            artist.set_title(props["title"])
            artist.grid(bool(props["xgrid"]), axis="x")
            artist.grid(bool(props["ygrid"]), axis="y")
        elif kind == "line":
            artist.set_color(props["color"])
            artist.set_linewidth(props["linewidth"])
            artist.set_linestyle(props["linestyle"])
            artist.set_marker(props["marker"])
            artist.set_markersize(props["markersize"])
            artist.set_alpha(props["alpha"])
            artist.set_label(props["label"])
        elif kind == "text":
            artist.set_text(props["text"])
            artist.set_color(props["color"])
            artist.set_fontsize(props["fontsize"])
            artist.set_fontweight(props["fontweight"])
            artist.set_fontstyle(props["fontstyle"])
        elif kind == "legend":
            ax = artist.axes
            artist = ax.legend(
                loc=props["loc"],
                bbox_to_anchor=props["bbox_to_anchor"],
                ncols=props["ncols"],
                fontsize=props["fontsize"],
                frameon=props["frame_on"],
                borderpad=props["borderpad"],
                labelspacing=props["labelspacing"],
                handlelength=props["handlelength"],
                handletextpad=props["handletextpad"],
                borderaxespad=props["borderaxespad"],
                columnspacing=props["columnspacing"],
            )
            artist.set_visible(props["visible"])
            for text in artist.get_texts():
                if props["fontsize"] is not None:
                    text.set_fontsize(props["fontsize"])
            frame = artist.get_frame()
            frame.set_visible(props["frame_on"])
            frame.set_alpha(props["frame_alpha"])
            frame.set_facecolor(props["facecolor"])
            frame.set_edgecolor(props["edgecolor"])
        elif kind == "spine":
            artist.set_visible(props["visible"])
            artist.set_edgecolor(props["color"])
            artist.set_linewidth(props["linewidth"])

    fig.canvas.draw_idle()
    return fig
'''
